### ISSUE TITLE
async / await command APIs

### ISSUE THREAD

**Issue by joshuawright11** [swift-server/RediStack#108]
Are there plans to add `async`/`await` versions of the existing `EventLoopFuture` [commands](https://github.com/swift-server/RediStack/tree/main/Sources/RediStack/Commands)?

I'd be happy to add them if it's something folks would be interested in.

i.e.
```swift
extension RedisClient {
    public func echo(_ message: String) async throws -> String {
        echo(message).get()
    }
}
```

**Comment by joshuawright11** [comment]
went ahead and implemented [here](https://github.com/swift-server/RediStack/pull/109)

**Comment by danivideda** [comment]
Is this repo still maintained btw? It's a shame that Swift still lack adoption outside of the Apple ecosystem :(
