### ISSUE TITLE
error when setting a key to json string

### ISSUE THREAD

**Issue by yspreen** [swift-server/RediStack#84]
ERR Protocol error: expected '$', got '+'

I'm setting `door_uuid` to `{"locked":true,"open":false}`
(where uuid is a uuid)

**Comment by yspreen** [comment]
false flag. two issues from my end:

1. I tried to set `RESPValue.simpleString(.init(string: "val")` instead of just `"val"`
2. apparently if I have a pubsub open, that needs its own redis connection and send commands have to happen on another connection.

**Comment by fabianfett** [comment]
@yspreen Great you found the underlying issue. If that issue isn't resolved please reopen this issue.
