### ISSUE TITLE
How do I connect using tls?

### ISSUE THREAD

**Issue by Kuari** [swift-server/RediStack#96]
I was ready to use TLS to connect, but I kept getting a clue. I've noticed that version 1.5 of release even adds nio-ssl as the default dependency, but so far I've been trying for hours and don't understand how to use TLS connections.
Maybe this is a very basic question, but I can't find a relevant post and can't find a relevant answer, can you prompt me, thank you!

**Comment by Kuari** [comment]
![image](https://github.com/swift-server/RediStack/assets/25321169/496f9773-e8d9-4e1c-8555-79b4fbb32035)
I found the TLS configuration in PR 4 years ago, but it doesn't exist today.
Currently in the source code, I only see the configuration of tls in the connection to the cluster.
Do I understand it wrong? I'm really confused.😭

**Comment by Joannis** [comment]
Hello @Kuari, you're right in that it's not supported yet. It's planned to be supported, and I believe it's been starting up as part of the Redis Cluster support. But unfortunately there's no API you can use at this point.

**Comment by Kuari** [comment]
Thank you for your reply and your efforts. I'm looking forward to the new features coming.
